# Generated by Django 5.2.6 on 2025-09-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='peliculas/', verbose_name='Imagen')),
                ('fecha_estreno', models.DateField(blank=True, null=True, verbose_name='Fecha de estreno')),
            ],
        ),
    ]
